language: common-lisp
sudo: true
env:
  matrix:
    - LISP=abcl
    - LISP=sbcl # COVERALLS=true
    - LISP=ccl
    - LISP=clisp
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=abcl  # JVM build goes wrong too many times
    - env: LISP=ccl   # I need to figure out how to test read-print behaviour correctly
    - env: LISP=clisp # wait for cl-coveralls dependencies to support it
    - env: LISP=cmucl # wait for CIM to support it
    - env: LISP=ecl   # wait for cl-coveralls dependencies to support it

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  - git clone https://github.com/EuAndreh/cl-intbytes.git   # wait until in Quicklisp

script:
  - cl -l prove -l cl-coveralls -l cl-bson
       -e '(setf prove:*debug-on-error* t
                 *debugger-hook* (lambda (c h)
                                   (declare (ignore c h))
                                   (uiop:quit -1)))
           (or (coveralls:with-coveralls (:exclude "t")
                 (prove:run :cl-bson-test))
               (uiop:quit -1))'
